### PR TITLE
fix bug of LightweightSemaphore::wait(timeout)

### PR DESCRIPTION
**Pull request by qinzuoyan**

### CODE REVIEW

**Comment by imzhenyu** [comment]
I don't get it about the fix for LightweightSemaphore::Wait(timeout). Would you mind explaining a little bit? Btw, the code is now copied into rDSN, and this branch won't be pulled when building rDSN. It is best if we directly work on the rDSN copy in this case.

**Comment by qinzuoyan** [comment]
I see that the code is merged into rDSN, but I still commit here bcz I need to add the test code. I have also committed it into rDSN.

Simply explain: 
1, tryWait() may fail if oldCount > 0 but m_count.compare_exchange_strong() fails, just when another thread modified the value recently.
2, in wait(timeout), if tryWait() fails for the above reason, then oldCount > 0, but in the previous implementation it still calls m_sema.wait(timeout) to invoke kernal sem_wait().
3, then, even some other thread calls signal(), it would not call m_sema.signal() to wake the waiting thread.

The above is just one scene, and the real world is more complicated. I'm not sure whether my fix is fully correct, but it is a tip :)

**Comment by qinzuoyan** [comment]
In addition, because wait(timeout) may return false for timeout reason, we should maintain the counter carefully:
1, the following code seems no problem:

```
        if (tryWait())
            return true;
        int oldCount = m_count.fetch_sub(1, std::memory_order_acquire);
        if (oldCount > 0)
            return true;
```

2, but next, when invoke m_sema.wait(timeout), it may fails for EINTR or ETIMEOUT reason, both cases indicate that we are not allowed to consume the counter, so we should return the counter by invoke signal(). So as it:

```
        if (m_sema.wait(timeout_milliseconds))
            return true;
        signal();
        return false;
```

The test code 'tests/lostwakeup2' can reproduce the original bug (by revert 'common/seme.h' to the old version) and validate the fix.

**Comment by imzhenyu** [comment]
I see - u r right. Previously we have missed the maintenance of  the counter. Thanks~

**Pull request merged**
